version: 2
updates:
  # Configurazione per il backend (Node.js)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

  # Configurazione per il frontend (Node.js)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope" 