[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_BACKEND_URL = "https://edilconnect-backend.herokuapp.com" # Questo URL dovrà essere aggiornato con il tuo backend effettivo